group:
  # JavaScript files
  - files:
      - source: sync-files/js/.github/
        dest: .github/
        exclude: |
          workflows/bundlewatch.yml
          bundlewatch.config.json
      - source: sync-files/js/.eslintignore
        dest: .eslintignore
      - source: sync-files/js/.eslintrc.json
        dest: .eslintrc.json
      - source: sync-files/js/.releaserc
        dest: .releaserc
    repos: |
      googlemaps/js-ogc
      googlemaps/js-markerwithlabel
      googlemaps/js-markermanager
      googlemaps/js-three
      googlemaps/js-api-loader
      googlemaps/js-polyline-codec
      googlemaps/js-jest-mocks
      googlemaps/js-markerclustererplus
      googlemaps/react-wrapper
  # Browser only JavaScript files
  - files:
      - source: sync-files/js/.github/
        dest: .github/
      - source: sync-files/js/.babelrc
        dest: .babelrc
    repos: |
      googlemaps/js-ogc
      googlemaps/js-markerwithlabel
      googlemaps/js-markermanager
      googlemaps/js-three
      googlemaps/js-api-loader
      googlemaps/js-polyline-codec
      googlemaps/js-markerclustererplus
