name: Sync Files
on:
  push:
    # branches:
    #   - master
    #   - main
  schedule:
    - cron: "0 14 * * MON"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: jpoehnelt/repo-file-sync-action@4b8e3d8668cd42d0d1225f2f7c2d134ff0892cc4
        with:
          GH_PAT: ${{ secrets.GOOGLEMAPS_BOT_REPO_TOKEN }}
          GIT_EMAIL: "googlemaps-bot@google.com"
          GIT_USERNAME: "googlemaps-bot"
          COMMIT_PREFIX: "chore: "
          OVERWRITE_EXISTING_PR: true
          CONFIG_PATH: .github/sync-files.yml
          BRANCH_PREFIX: file-sync
          DRY_RUN: true
          PR_LABELS: |
            file-sync
            merge
