name: Sync Secrets
on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: google/secrets-sync-action@v1.1.0
      name: Sync Secrets Run ID
      with:
        SECRETS: |
          ^SYNCED_
        REPOSITORIES: |
          ^googlemaps
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_REPO }}
      env:
        SYNCED_RUN_ID: ${{github.run_id}}
        SYNCED_GITHUB_TOKEN_REPO: ${{github.GITHUB_TOKEN_REPO}}
